### ISSUE TITLE
Add the ability to only install with dev

### ISSUE THREAD

**Issue by ragingdave** [jakoch/phantomjs-installer#10]
Given that there is no way to specify not to install phantomjs. 
I wanted to reach out first to see if this was something you would be interested in, before putting together a pr.
For instance maybe the post-install-cmd can have an additional param like --dev-only, to allow the same composer file to be usable for a prod installation and dev installation.  And this would not be a breaking change as the default behavior would be maintained but allow for those that don't need phantomjs in all instances to not have it install.
Another option could be to base the install off of the --dev or --no-dev switch to decide when to install this, but this would end up being a breaking change potentially.

**Comment by Laykou** [comment]
You can create your custom autoload function in which you will check if phantomJS is available and if yes run the phantom's install script:

```PHP
// src/Installer.php
<?php
namespace App;

class Installer
{
    public static function postInstall()
    {
        if (class_exists('\PhantomInstaller\Installer')) {
            \PhantomInstaller\Installer::installPhantomJS();
        }
    }
}
```

and replace in your `composer.json`:

```JSON
"scripts": {
        "post-install-cmd": [
            "App\\Installer::postInstall"
        ],
        "post-update-cmd": [
            "App\\Installer::postInstall"
        ]
    },
```

As far as I know this is the only way how to deal with dev installers. For example the [CakePHP 3.0](https://github.com/cakephp/cakephp) framework also [solves the problem in the same way](https://github.com/cakephp/app/blob/84f6012e4f0aab3a172c9c12175c5f183e2ba7d1/src/Console/Installer.php#L66-L68).

**Comment by jakoch** [comment]
:+1:  Absolutely, an application installer might also do the job. Good solution.

**Comment by jakoch** [comment]
Update: 

This plugin: https://github.com/neronmoon/scriptsdev enables you to do the following:
```
"scripts-dev": {
        "post-install-cmd": [
            "App\\Installer::postInstall"
        ],
        "post-update-cmd": [
            "App\\Installer::postInstall"
        ]
    },
```
