### ISSUE TITLE
Failed to copy vendor/jakoch/phantomjs/phantomjs.exe on install

### ISSUE THREAD

**Issue by Laykou** [jakoch/phantomjs-installer#13]
I'm running the `composer update` on `Windows 7` and I got the following issue:

```
Generating autoload files
  - Installing phantomjs (2.0.0)
    Loading from cache

Script PhantomInstaller\Installer::installPhantomJS handling the post-update-cmd event terminated with an exception



  [ErrorException]
  copy(./vendor/jakoch/phantomjs/phantomjs.exe): failed to open stream: No such file or directory
```

The real `phantomjs.exe` file is actually in folder `./vendor/jakoch/phantomjs/bin/phantomjs.exe` so there might something change in the phantomjs repo. I guess it happens when copying/bypassing the phnatomjs.exe file into bin folder.

**Comment by jakoch** [comment]
Thank you for reporting the issue.
Yes, the folder layout changed. 
The file location depends on the version - i will add a check.
