### ISSUE TITLE
Support the  config.vendor-dir setting in composer.json

### ISSUE THREAD

**Issue by mattbryson** [jakoch/phantomjs-installer#15]
If you have a different vendor dir defined in your composer.json, this is NOT used when downloading the chosen build of phantomJS.

The phantomJS installer package is installed correctly, but the package it subsequently downloads is always downloaded to a root /vendor folder.

I have  

````javascript
{
  "config": {
     "vendor-dir": "app/vendor"
    }
}
````

But after install I have the following folder structure...

`````
app
  - vendor
    - jakoch
      - phantonjs-installer
vendor
  -jakoch
    - phantomjs
`````

where as it should be

`````
app
  - vendor
    - jakoch
      - phantonjs-installer
      - phantomjs    
`````

**Comment by jakoch** [comment]
Yes, the `config.vendor-dir` is not taken into account, only `config.bin-dir`.
The vendor dir is hardcoded  atm, see https://github.com/jakoch/phantomjs-installer/blob/master/src/PhantomInstaller/Installer.php#L25
It just needs the vendor-dir as prefix and `.\vendor` removed.

**Comment by jakoch** [comment]
Give this a try:
```
{
    "require": {
        "jakoch/phantomjs-installer": "dev-master"
    },
    "scripts": {
        "post-install-cmd": [
            "PhantomInstaller\\Installer::installPhantomJS"
        ],
        "post-update-cmd": [
            "PhantomInstaller\\Installer::installPhantomJS"
        ]
    },
    "config": {
        "bin-dir": "bin",
        "vendor-dir": "app/vendor"
    }
}
```

**Comment by mattbryson** [comment]
Awesome, thanks for the quick response, ill give it a go.
