### ISSUE TITLE
Do not try to re-install same PhantomJS version

### ISSUE THREAD

**Issue by igorsantos07** [jakoch/phantomjs-installer#17]
I've noticed that, after the first install, the scripts try to install again the same PhantomJS binary every time we mess around with Composer. Would be better if it noticed there was no need to update anything, and skip that procedure.

**Comment by jakoch** [comment]
Yes, true, the file is downloaded to the cache - and then each time overwritten from the cache.

- [ ] add "if file exists, skip overwriting"

**Comment by vesper8** [comment]
+1

**Comment by iainp999** [comment]
Another +1 here

**Comment by InputOutput** [comment]
yes please +1

**Comment by jakoch** [comment]
Ok, i've added a version comparison between the requested version and the already installed version.

The installation of PhantomJS is skipped (on a second run of the installer), when the installed version is lower or equal to the version you are trying to install. 
Or in other words: only a newer version will be installed, if PhantomJS is already installed.

The changes are on the `dev-master` branch. (It's prepared as `2.1.1-p04` tag, but not tagged, yet.)

It would be nice, if you find the time to test this and provide some feedback. 

Best, Jens

**Comment by InputOutput** [comment]
Sure I'll give it a run

**Comment by InputOutput** [comment]
Looking good!




vagrant@backend:~/kaartje2go.nl/app$ composer update

[blablabla]

> PhantomInstaller\Installer::installPhantomJS
   - PhantomJS v2.1.1 is already installed. Skipping the installation.


vagrant@backend:~/kaartje2go.nl/app$ composer install

[blablabla]

> PhantomInstaller\Installer::installPhantomJS
   - PhantomJS v2.1.1 is already installed. Skipping the installation.
vagrant@backend:~/kaartje2go.nl/app$

**Comment by jakoch** [comment]
Thank for the quick feedback!
Let's tag it...
