### ISSUE TITLE
Stop/kill (and restart?) PhantomJS before updating it

### ISSUE THREAD

**Issue by igorsantos07** [jakoch/phantomjs-installer#18]
If you have PhantomJS running in background and you try to update any composer package, the install command will run and fail with a message stating the `phantomjs` binary is being used.

Would be nice if:
- the binary was stopped before the update procedure
  - not sure if it would be possible to start the binary again with the same settings (maybe getting the command that started it? That's viewable on `ps aux`)
- OR the script noticed it was running and gave a better warning instead of a `copy()` error

**Comment by jakoch** [comment]
Hey Igor!

Thank you this feature suggestion.
Yes, when the binary is being used during installation, then it's a file-lock and the copy operation will fail.

I'm a bit undecided about "automatic/silent" stopping of a running process from the installer.
On the one hand, it's kind of convenient from the installer perspective. It's nice, when things just work. On the other hand, it's not a good practice to shut things down without asking. 

For asking we could use Composers "dialog" feature. And you could force a yes for "automatic" shutdown and installation by using Composers CLI option `--no-interaction (-n): Do not ask any interactive question.`. That means that the default behavior of the installer would change to stop-and ask-what-to-do in the normal interactive mode.

Implementation-wise, the installer will need some additional functions:
   - `detectPhantomJsProcess()` (cross-platform)
   - two functions: `stopPhantomJs()` and maybe `startPhantomJs()` (cross-platform)
   - a function for `asking` using a CLI dialog
   - a function `skipInstallationIfProcessRunning()`, which could output a message like `PhantomJs is running. Installation skipped.`

What do you think?

**Comment by igorsantos07** [comment]
That makes sense, from my point of view.
I'm not sure how you would go to discover if the process is running cross-platform, but I guess it would help you to restart it once it's updated.
However, the idea of "daemon control" is not entirely true since it's not a daemon, only a background task. Thus, you would kill it and re-run it as needed.

The idea of a CLI dialog is great, so the user would not be inadvertently affected by a killed process.

Finally, an idea for simplification of solution would be: see if the binary is writable; if it's not, use a CLI Dialog to warn the user it could be running or not have writing permissions. The user would then kill/fix it and confirm, and the install procedure would continue.

**Comment by FelikZ** [comment]
:+1:  for `stopPhantomJs()` `startPhantomJs()`

**Comment by FelikZ** [comment]
Workaround:

```json
    "scripts": {                                                                                                                                                                                                
        "post-install-cmd": [                                                                                                                                                                                   
            "php -r \"exec('pkill phantomjs >/dev/null 2>&1');\"",                                                                                                                                              
            "PhantomInstaller\\Installer::installPhantomJS"                                                                                                                                                     
        ],                                                                                                                                                                                                      
        "post-update-cmd": [                                                                                                                                                                                    
            "php -r \"exec('pkill phantomjs >/dev/null 2>&1');\"",                                                                                                                                              
            "PhantomInstaller\\Installer::installPhantomJS"                                                                                                                                                     
        ]                                                                                                                                                                                                       
    }
```

**Comment by chris-gilmore** [comment]
I too have run into this issue:
```bash
failed to open stream: Text file busy
```
In the current code, we see the [copy](https://github.com/jakoch/phantomjs-installer/blob/f826b1fe7cc51497a0ee2d6b3de78314f79e380f/src/PhantomInstaller/Installer.php#L382) as:
```php
copy($targetDir . $sourceName, $targetName);
````
There is no need to stop any running `phantomjs` processes if we were to instead `unlink` the destination file before copying.
Alternatively, we could copy to a temp file first and then do an atomic `rename`.

**Comment by chris-gilmore** [comment]
jakoch, please fix.

**Comment by jakoch** [comment]
Please check, if `dev-master#eb2b8f8 as 2.1.1` works for you and replaces a running binary.
Thanks you for reminding me and thank you in advance for testing.

**Comment by chris-gilmore** [comment]
I just now tested and confirmed it works.
I first downgraded to 1.9.7 and ran phantomjs in interactive mode in the background and then tried to upgrade to 2.1.1-p08 and failed.
I then tried upgrading to "dev-master#eb2b8f8 as 2.1.1" and succeeded, confirming that it was able to replace a running binary.

**Comment by jakoch** [comment]
Thank you, Chris! 

I tagged a new version: v2.1.1-p09.
