### ISSUE TITLE
phantomjs binary fails on Mac OS Yosemite

### ISSUE THREAD

**Issue by reksc** [jakoch/phantomjs-installer#20]
This is related to https://github.com/ariya/phantomjs/issues/12928.

Reporting this to let others know that this package is not broken (my first impression) - it's a bug in phantom itself.

**Comment by Chekote** [comment]
Are you sure? I have this problem when using phantomjs-installer, but if I download PhantomJS from [here](http://phantomjs.org/download.html), it works perfectly.

**Comment by reksc** [comment]
Hi,

Perhaps it's related to the version that phantomjs-installer is pointing
to. The bug in phantomjs was well known and a fix was on it's way when I
opened the issue, so it's understandable that the official download page
provides a working copy.

I can't verify it atm :)

Cheers

2015-09-23 22:56 GMT+02:00 Donald Tyler <notifications@github.com>:

**Comment by jakoch** [comment]
I wonder why i got multiple highlights of this issue in my notification bar, even when there is no new content added here. Hmm?

I'm closing this, because (as pointed out by reksc): the broken package is a problem of the vendor.
(Maybe an old version works better: 
https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-macosx.zip)

**Comment by reksc** [comment]
I replied to an email notification about a comment left here. Turned out that it was most likely deleted by the author, so I decided to remove mine - as being out of context :).

I confirm that phantomjs v 1.9.7 worked ok.

**Comment by jakoch** [comment]
Thank you for explaining!

**Comment by Chekote** [comment]
Sorry for the confusion! I realized after posting that the two binaries were identical, so did some more digging and found that the phantomjs that I was running without issue was actually installed by brew.

So the official download is still broken.
