### ISSUE TITLE
Internal corruption of phar error when executing Composer post-install-cmd

### ISSUE THREAD

**Issue by Mattnmoore** [jakoch/phantomjs-installer#21]
When running `PhantomInstaller\Installer::installPhantomJS ` from the Composer post-install-cmd, it terminates with the following exception.

```
[UnexpectedValueException]
  internal corruption of phar "/vagrant/viralstyle/vendor/jakoch/phantomjs/976533866d151c9ee82fd48df27c585d.bz2" (__HALT_COMPILER(); not found)
```

**Comment by jakoch** [comment]
Hey Matt!

Thank you for reporting this issue. 

We utilize the Composer API for download and extraction of the PhantomJS archives.

The relevant lines of code are https://github.com/jakoch/phantomjs-installer/blob/master/src/PhantomInstaller/Installer.php#L56-L57
There is not much i could change or fix there regarding this file type.

After a quick glance at the problem i guess that `.tar.bz2` files are not correctly handled by `composer.phar` itself, which uses ArchiveDownloader / TarDownloader in this case.
So, when we go one level up, the origin of the error should/could be here: 
https://github.com/composer/composer/blob/master/src/Composer/Downloader/TarDownloader.php#L28-L29

So, Composer relies on the PharData API for the extraction. 
Maybe the underlying PHP method `PharData::extractTo()` is somehow flawed.
Not sure.

I suggest to reproduce the issue using different PHP versions.
Do this error occur on all PHP versions?

**Comment by jakoch** [comment]
The issue doesn't happen on Travis, while using several PHP version.
Can not reproduce.
Closing.
