### ISSUE TITLE
Generate class on install with path to installed binary

### ISSUE THREAD

**Issue by hstonge** [jakoch/phantomjs-installer#22]
Hi, I must first begin by thanking you for this great package; it really eases the process of deploying PhantomJS on various PHP projects...

To make things even easier, there could be an auto-generated class that would expose a constant defined to the absolute path where the binary was installed. Usage could be:
```php
use PhantomInstaller\PhantomBinary;
$path = PhantomBinary::ABSOLUTE_PATH;
```

This behavior could be based on the [phantomjs module](https://github.com/Medium/phantomjs/blob/master/install.js#L93), which does exactly this in Node.js.

**Comment by wmcmurray** [comment]
:+1:

**Comment by jakoch** [comment]
Glad you like the installer and thank you for the feature suggestion.

**Comment by jakoch** [comment]
Ok - implemented.

When the binary is copied a new PHP file is dropped into the package folder.
The Composer Autoloader should pick it up during autoloading generation.
The dropped file should then be available via autoloading.
Like you suggested, the file might then be included by a simple `use` statement.

- trigger the autoloading with

        use PhantomInstaller\PhantomBinary;

- the class supports access to the following constants

        $bin = PhantomInstaller\PhantomBinary::BIN;
        $dir = PhantomInstaller\PhantomBinary::DIR;

- the class supports access to the constants through static functions

        $bin = PhantomInstaller\PhantomBinary::getBin();
        $dir = PhantomInstaller\PhantomBinary::getDir();

Please give me feedback, if this works out for you.

Best, Jens

**Comment by hstonge** [comment]
Hi Jens,

Testing by using the following _composer.json_:
```json
{
    "require": {
        "jakoch/phantomjs-installer": "dev-master"
    },
    "scripts": {
        "post-install-cmd": [
            "PhantomInstaller\\Installer::installPhantomJS"
        ],
        "post-update-cmd": [
            "PhantomInstaller\\Installer::installPhantomJS"
        ]
    }
}
```
and running `composer install` effectively generates a _PhantomBinary.php_ file, but it seems to be saved in the wrong directory.

According to your package's autoload rule (`"PhantomInstaller\\": "src/"`), it should be saved into:
`vendor/jakoch/phantomjs-installer/src/PhantomInstaller`, not
`vendor/jakoch/phantomjs`.

Trying to execute the following:
```php
<?php
require('vendor/autoload.php');
use PhantomInstaller\PhantomBinary;
$bin = PhantomInstaller\PhantomBinary::BIN;
```

yields `Fatal error: Class 'PhantomInstaller\PhantomBinary' not found [...]`

**Comment by jakoch** [comment]
Thanks you for testing and feedback!  You are right!

I think `$targetDir` isn't needed at all and i just drop the file into the current `__DIR__`.

**Comment by hstonge** [comment]
Working great now! Of course, I've only tested on Mac OS X Mavericks & Yosemite, but the change seems quite straightforward and multi-env compliant.

**Comment by jakoch** [comment]
You are welcome. 

And thank you again for the feature suggestion.
I think the downstream users will find this quite helpful to pick the binary up.

Best, Jens
