### ISSUE TITLE
Don't force install to /vendor folder

### ISSUE THREAD

**Issue by mtpultz** [jakoch/phantomjs-installer#23]
For a couple of our projects the Composer folder is not `/vendor`, but `/vendors`, or in some cases named completely different.  In composer.json the folder is set using `vendor-dir`.  Is it possible to not hard code the vendor directory and instead read it from composer.json?  So it would allow `/whateverMyFolderNameIs` and then also use `/whateverMyFolderNameIs/bin`.

**Comment by jakoch** [comment]
Hey Martin,

yes, its possible to define a custom name for the vendor folder.
The installer takes the `vendor-dir` setting into account. (Its not hard-coded.)
If you leave it away, the Composer default is used: `./vendor`.
See https://github.com/jakoch/phantomjs-installer/blob/master/src/PhantomInstaller/Installer.php#L43

`composer.json`
```
    "config": {
        "bin-dir": "my-binaries",
        "vendor-dir": "my-vendors"
    },
```

**Comment by mtpultz** [comment]
Thanks @jakoch, I'm pulling in `dev-master` now.
