### ISSUE TITLE
Latest version of phantomjs not available for OS...

### ISSUE THREAD

**Issue by davidjeddy** [jakoch/phantomjs-installer#25]
CentOS release 6.7 (Final) x64

Logic does a good job of detecting the OS and the most recent stable release of phantomjs. However, there is no stable release at the current version for the OS detected.

```BASH
 [Composer\Downloader\TransportException]                                                                                                          
  The "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2" file could not be downloaded (HTTP/1.1 404 NOT FOUND)
```

...per https://bitbucket.org/ariya/phantomjs/downloads/

Solution: if the request returns anything other than status 200, tick down one version and try again but no go below the lowest supported version.

**Comment by jakoch** [comment]
Hey David,

yes, its a know issue, see #12.

Your solution of automatically re-trying the download while lowering the version number
is a great idea. I wonder why nobody came up with that, yet. 

Ok, lets see how we could implement that:
- we need an array for versions, ordering high to low
- the retry is based on the return value of the Composer Downloader
- foreach versions as version - download()
  - if download failed, message (download not found) and continue
  - else return

Did i mess up? Suggestions welcome..

**Comment by jakoch** [comment]
Follow up:

if i extend that idea a bit, we could re-try the same version, but use a fallback URL, right?
That would address https://github.com/jakoch/phantomjs-installer/pull/24

- 2.0.0 - original download source
- 2.0.0 - eugene or vitalliums source
- then go lower 1.9.8

**Comment by jakoch** [comment]
Ok, i checked the Composer Downloader API.
It doesn't return a value we could work with.
https://github.com/composer/composer/tree/master/src/Composer/Downloader

**Comment by davidjeddy** [comment]
Personally, I would not depend on the custom releases for a production system. IE if your goal for phantom is to be at the level of, for example, Selenium go with the source teams releases.

Try for current version, if failed step back 0.1.0 and try for the next oldest version.

This is my personal opinion of course.

**Comment by davidjeddy** [comment]
Any movement on this?

**Comment by jakoch** [comment]
Ok, i've implemented download retrying with lowering the version numbers.

The call to `Composer\DownloadManager->download()` is now wrapped in a `while` loop.
The inital while expression is the number of phantomjs versions,
which is basically the maximum number of download retries.
The phantomjs versions are hardcoded in `static function getPhantomJsVersions()`.
If the download succeeds, we  simply break out of the try/catch.
But, if a `Composer\Downloader\TransportException` with HttpStatusCode 404 happens,
we get the next lower version from the versions array from `getLowerVersion()`,
init a new in memory package with that version and url ... and try again. 

Not sure, if that will work out :) But its alive on dev-master and needs testing and feedback.
All bugfixes welcome.

Best, Jens

**Comment by davidjeddy** [comment]
Almost...

```BASH
[163.0MB/87.10s]     Downloading: Connecting...[163.1MB/87.41s] Script PhantomInstaller\Installer::installPhantomJS handling the post-update-cmd event terminated with an exception

                                                                                                                                                    
  [Composer\Downloader\TransportException]                                                                                                          
  The "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2" file could not be downloaded (HTTP/1.1 404 NOT FOUND)  
                                                                                                                                                    
```

**Comment by jakoch** [comment]
You may find an example `composer.json` for triggering a "2.0.0" to "1.9.8" tickdown here:
https://github.com/jakoch/phantomjs-installer/blob/master/tests/example-v2.0.0-v1.9.8/composer.json

Referencing the [version lowering on the PHP7 branch](https://travis-ci.org/jakoch/phantomjs-installer/jobs/105036286#L238) from this [build matrix](https://travis-ci.org/jakoch/phantomjs-installer/builds/105036282).

Please give me a little feedback, if its also working on your side.
Thanks, Jens
