### ISSUE TITLE
Alternative approach

### ISSUE THREAD

**Issue by SamMousa** [jakoch/phantomjs-installer#36]
I would like to be able to use this package without the extra configuration steps currently required.
I think this could be done in the following way:
1. Install the composer package
2. The composer package installs a wrapper in the `bin` directory.
3. When launched the wrapper downloads (if applicable) the latest phantomjs.
4. The wrapper launches phantomjs, passing any arguments it received.

This would allow for simpler usage and faster installation at a slight cost for actual launch.

**Comment by jakoch** [comment]
Hey Sam,

the installation script is triggered with a Composer event binding only for convenience.
So, if you want to get rid of the scripts section, you can already do this.
That saves you a few lines in composer.json and get's rid of the automatic triggering. 

To get closer to the behavior you described (in points 2 and 3) we could add a `/bin/install-phantom` script for convenience, which calls the installer (`PhantomInstaller\\Installer::installPhantomJS`). 
If you need it, let's add it... feature request accepted.

But i'm undecided, if an installer project should also provide an invocation wrapping layer for the binary. That's basically going into the direction of #18 (starting/stoping phantom). 
I still think that's something for a downstream project, e.g. an already existing one (jonnnnyw/php-phantomjs or similar) or a new project/repository `phantomjs-bin`. This project could then provide the bin wrapper and the bin script for the invocation could make use of the  `bin/install-phantom` script of the installer.

**Comment by SamMousa** [comment]
Hmm; I like the convenience script.

What's the downside of a wrapper? Especially if it is transparant (essentially being the same as a symlink from a user perspective)

**Comment by jakoch** [comment]
(I was thinking of a PHP layer wrapping the binary).
Your wrapper is just a little shell or batch script to invoke the executable and forward parameters, right? There is no downside. And that's basically issue #14, where the executable remains in the vendor folder after installation. It's not copied, but Composer creates a symlink to the executable in the binary folder.

**Comment by SamMousa** [comment]
@jakoch, yes the only added thing the wrapper should do before that (in my opinion) is checking for updates / downloading phantomjs.
Ideally the update check would be cached for say an hour

This makes it work more intuitively and you could think of it as kind of a deferred installation; until you actually run phantomjs it is not installed but when you do it is installed.

**Comment by jakoch** [comment]
Hmm.. i'm not sure how and where the update check fits in.

Let's say we have a `/bin/run-phantom` wrapper, 
which tests, if the executable was already installed, if not installs it using `/bin/install-phantom` 
and then forwards CLI arguments to the original symlink `/bin/phantom`, which runs the exe.

**Comment by SamMousa** [comment]
Basically what you said, if it can check if the executable was already installed I assume that it can also check if it that's the latest version, right ?

**Comment by jakoch** [comment]
We would need to ask for the version information and compare it (version of the installer to latest version)
Probably using an API request to Github retrieving the latest version from Github Releases.

**Comment by jakoch** [comment]
I don't see the need to work a "deferred installation" solution, which fetches the binary on first use.
And due to the low update release frequencies of PhantomJS itself, you always get the latest version here.
I also don't see the need to work on an additional update check for newer PhantomJS version, because it's very easy to add a new version number manually.
Closing.
