### ISSUE TITLE
Silent error when download fails with status other than 404

### ISSUE THREAD

**Issue by shark0der** [jakoch/phantomjs-installer#42]
The install was silently failing (no errors, just downloading and then nothing) and I wasn't able to figure out why phantom is not getting installed until I `var_dump`-ed the exception.

I believe [this line](https://github.com/jakoch/phantomjs-installer/blob/master/src/PhantomInstaller/Installer.php#L195) should be changed to

`if ($e->getStatusCode() !== 200) {`

**Comment by jakoch** [comment]
Thank you for the report.
Can you do a `var_dump($e);`, because i'd like to know the `TransportException` issue you are facing.

**Comment by jakoch** [comment]
Ok, code updated.
I want to handle exactly the TransportException 404 case. 
 - https://github.com/jakoch/phantomjs-installer/blob/c53b65b806ae995ad2a73576a65a23bb11789f45/src/PhantomInstaller/Installer.php#L195-L197
Additionally all other TransportExceptions are now reported (unsilenced) with their HTTP status code, see change. 

Is that ok for you?

**Comment by shark0der** [comment]
Can't `var_dump` it anymore as it was a temporary network error and I can't reproduce it, but the code looks good to me!

Thanks!
