### ISSUE TITLE
Not catching error TransportException

### ISSUE THREAD

**Issue by nass600** [jakoch/phantomjs-installer#43]
Hi,

I am running your script via a http://robo.li task. When getting a TransportException, it is controlled by your script and not re-thrown so there is no stderr output and therefore Robo is not detecting a failure.

If I re-throw the error in your script then the stderr output is as expected.

What do you think about it?

**Comment by jakoch** [comment]
Hi Ignacio,

let's see... 

We are talking about [src/PhantomInstaller/Installer.php#L201](https://github.com/jakoch/phantomjs-installer/blob/c53b65b806ae995ad2a73576a65a23bb11789f45/src/PhantomInstaller/Installer.php#L201), right? 

When you get a TransportException, then Composer's `$io->error()` function writes the message to the error output.  That's based Composer's proc_open stream buffering approach to provide access to the output streams. I'm not familiar with Robo's API, but it should have a method somewhere, which provides access to the stdError stream, too. That would allow you to handle the error message.

I would try to solve this by monitoring the std error output with methods provided by Robo, 
rather then by re-throwing an exception from my plugin.

Regards Jens

**Comment by nass600** [comment]
Thanks @jakoch for the quick response.

Yeah, I had the chance to get deeper into the code and doing some debugging on Robo. They use Symfony Process component for executing the commands and it seems the stderr is not being handled the right way AFAIK so it is messing with the composer output.

Sorry to bug you with this

**Comment by jakoch** [comment]
You're welcome.
