### ISSUE TITLE
 File does not exist or is not executable: /Users/.../vendor/bin/phantomjs 

### ISSUE THREAD

**Issue by am0nshi** [jakoch/phantomjs-installer#45]
Hi @jakoch 
Currently trying to install phantomjs according to instruction, and have next error:
 File does not exist or is not executable: /Users/.../vendor/bin/phantomjs 
Is package still actual?

**Comment by jakoch** [comment]
Yes, works. See https://travis-ci.org/jakoch/phantomjs-installer/builds/447474791

Try to run Composer in verbose mode to get some more output (by  using `composer install -vvv --profile`).
