### ISSUE TITLE
Composer 2 support

### ISSUE THREAD

**Issue by Seldaek** [jakoch/phantomjs-installer#47]
As composer 2 is coming, it would be good to support it here.

From looking at your code, IMO the best way would be to tag a new release 2.0, which supports Composer 1, and 2 together. You can check  `if (defined('Composer\Composer::RUNTIME_API_VERSION') && version_compare(Composer\Composer::RUNTIME_API_VERSION, '2.0', '>=')) { ..composer2 behavior .. } else { composer 1..}`

For v2, you can not just call download as in https://github.com/jakoch/phantomjs-installer/blob/master/src/PhantomInstaller/Installer.php#L190 - that will not do what you want anymore, and it uses async code which is rather messy to tap into like that.

You should instead do this:

```
$loop = $composer->getLoop()
$promise = $installationManager->download($package, $targetDir);
if ($promise) {
    $loop->wait(array($promise));
}
$promise = $installationManager->prepare('install', $package, $targetDir);
if ($promise) {
    $loop->wait(array($promise));
}
$promise = $installationManager->install($package, $targetDir);
if ($promise) {
    $loop->wait(array($promise));
}
$promise = $installationManager->cleanup('install', $package, $targetDir);
if ($promise) {
    $loop->wait(array($promise));
}
```

As an aside, I wonder if it wouldn't be better to let users specify the version they want to install in the root package's extra (like you have cdnurl option right now), instead of having a direct mapping of package version to phantomjs version..

**Comment by jakoch** [comment]
Thank you for looking at the code and providing these upgrade hints, Jordi! ❤️ 

> $loop = $composer->getLoop()

Whoaa.. this is new! Finally, we can reach the inner download loop. 

> let users specify the version they want to install in the root package's extra

Yes, that's way cleaner and also easy to add. TY for the suggestion.

**Comment by dereuromark** [comment]
Hey guys
We checked composer v2 compatibility and stumbled upon this ticket.
It seems this one here is the only issue left for us to try and use v2.

Is there any plan from your side to release a new version here based on the fix above?
Thank you!

**Comment by jakoch** [comment]
Composer 2 support landed.

I removed the direct mapping of package version to phantomjs version.
To indicate the BC break i'v tagged the version as v3.0.0.
