### ISSUE TITLE
Composer 2.0.9 not installing PhantomJS

### ISSUE THREAD

**Issue by JackPot777** [jakoch/phantomjs-installer#50]
Please take a look, fix it.

[https://github.com/composer/composer/issues/9698](url)

**Comment by jakoch** [comment]
You might want to work on your bug reporting skills.

Seems you require my package via "jonnnnyw/php-phantomjs"
and it's require statement is simply outdated, see https://github.com/jonnnnyw/php-phantomjs/blob/master/composer.json#L22
Big thanks to Jordi for tracking this down ! 

Referencing: https://github.com/jonnnnyw/php-phantomjs/issues/288

**Comment by CaptAm** [comment]
I came here, searching for solution to same reason - composer v.2.0.11 throws same error, as described in https://github.com/composer/composer/issues/9698
I was doing clear install, with new composer and PhantomJS as the only package, following the latest install information as of today: http://jonnnnyw.github.io/php-phantomjs/4.0/2-installation/
Right now working solution was to downgrade composer with: 
sudo composer self-update 1.9.2
BTW, using  https://github.com/jonnnnyw/php-phantomjs/blob/master/composer.json file was not successful, complaining about "src" directory.

**Comment by jakoch** [comment]
Maybe just use one of the forked repositories, which already updated the required version... 
- https://github.com/Weblanceur/php-phantomjs
- https://github.com/onsetsoftware/php-phantomjs
